### PR TITLE
freeze requirements

### PR DESCRIPTION
**Pull request by mvanveen**
`docker-compose up --build` was failing.  Freezing requirements for `django-celery` and `celery` to last known stable version fixes the problem.

### CODE REVIEW

**Comment by ingenieroariel** [comment]
My suggestion is to freeze requirements for all the dependencies that you
care about, for reproducible builds.

**Comment by mvanveen** [comment]
@ingenieroariel Yeah, thanks for that suggestion.  Agree there's some more to be done here around requirements freezing.  I tried to keep this change more or less specifically honed to the error I was experiencing in my build.

@jsvrcek @jj0hns0n : do you guys mind if I go ahead and freeze more of these packages?

**Comment by mvanveen** [comment]
Update: synced up with Joe we're gonna freeze all the things :)

**Pull request merged**
