### PR TITLE
Added management command "shutdown_celery_workers" to invoke task "gracefully_shutdown_workers".

### PR DESCRIPTION
**Pull request by JivanAmara**

### CODE REVIEW

**Comment by jsvrcek** [comment]
Are we able to add some tests to this?

**Comment by JivanAmara** [comment]
Since it affects the infrastructure it would require some significant additions to the test scripts to deal with containers exiting & detecting that.  There isn't really much new code to test & mocking wouldn't have any value.

**Comment by jsvrcek** [comment]
This doesn't seem to block new tasks from getting picked up to test I brought up the environment.
`docker-compose up -d`
Then submitted a job. 
Then killed the workers with the command:
`docker-compose run --rm celery python manage.py  shutdown_celery_workers`
It reads "Waiting for workers to finish up...".
I then submit a second job.   The second job gets picked up.  Both jobs finish and then the workers shutdown. 
I think what would be desired is that the jobs get placed on the main queue, but existing workers (i.e. active workers when shutdown_celery_workers was called), shouldn't pick up new work, otherwise they may be kept alive forever by new work. 

Please let me know if I made some sort of mistake in testing.  Thanks.

**Comment by JivanAmara** [comment]
Managed to recreate the issue, looking into why the cancel_consumer() call isn't working.

**Pull request closed without merging**
